CREATE TABLE SELLS (
    SNO INT,
    PNO INT,
    PRIMARY KEY (SNO, PNO),
    FOREIGN KEY (SNO) REFERENCES SUPPLIER(SNO),
    FOREIGN KEY (PNO) REFERENCES PART(PNO)
);
INSERT INTO SELLS (SNO, PNO) VALUES
(1, 1),
(1, 2),
(2, 4),
(3, 1),
(3, 3),
(4, 2),
(4, 3),
(4, 4);
